apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brunost.fullname" . }}-judge
  labels:
    {{- include "brunost.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.judge.apiToken | quote }}
  callback-secret: {{ .Values.judge.callbackSigningSecret | quote }}
  artifact-access-key: {{ .Values.artifacts.accessKey | quote }}
  artifact-secret-key: {{ .Values.artifacts.secretKey | quote }}
