{{- if .Values.workerDefaults.podDisruptionBudget.enabled }}
{{- range .Values.workers }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "brunost.fullname" $ }}-worker-{{ .name }}
  labels:
    {{- include "brunost.labels" $ | nindent 4 }}
    app.kubernetes.io/component: worker
    brunost.io/worker-class: {{ .name | quote }}
spec:
  maxUnavailable: {{ $.Values.workerDefaults.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      brunost.io/worker-class: {{ .name | quote }}
      {{- include "brunost.labels" $ | nindent 6 }}
{{- end }}
{{- end }}
