apiVersion: v1
kind: Service
metadata:
  name: {{ include "brunost.fullname" . }}-judge
  labels:
    {{- include "brunost.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: {{ .Values.monitoring.enabled | quote }}
    prometheus.io/path: {{ .Values.monitoring.path | quote }}
    prometheus.io/port: {{ .Values.monitoring.port | quote }}
spec:
  selector:
    app.kubernetes.io/component: judge
    {{- include "brunost.labels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.judge.port }}
      targetPort: http
