{{- range .Values.workers }}
{{- $config := get $.Values.nodeConfigs (printf "%s" .name) | default "{}" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brunost.fullname" $ }}-node-{{ .name }}
  labels:
    {{- include "brunost.labels" $ | nindent 4 }}
type: Opaque
stringData:
  node.json: {{ $config | quote }}
{{- end }}
