apiVersion: v1
kind: Service
metadata:
  name: {{ include "brunost.fullname" . }}-platform
  labels:
    {{- include "brunost.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: platform
    {{- include "brunost.labels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.platform.port }}
      targetPort: http
